[YottaDB/Lang/YDBPython#32] Fix test_ctrl_c and test_fatal_signal test failures due to YottaDB/DB/YDB@ae2721d8
Background
----------
* After YottaDB/DB/YDB@ae2721d8, the YDBPython pipeline failed in the `test_fatal_signal` test when the
  random signal chosen to terminate the process was `SIG-15`/`SIGTERM`.

* This was fixed by YottaDB/DB/YDB@7b0d93a3.

* Even after that fix, the `tests/test_fatal_signal.py::test_fatal_signal` test failed the pipeline once
  in a while when it randomly chose the `SIG-2`/`SIGINT` signal to terminate the process.

* Additionally, the `tests/test_yottadb.py::test_ctrl_c` test also failed randomly in a similar fashion.

* Both the failure symptoms were the following.

  ```
  Error in both is similar to: AssertionError: assert 1 == 254
  ```

Issue
-----
* The `test_ctrl_c` test failure is simpler to describe so I will use that below.

* Whenever the `test_ctrl_c` test failed, below was the failure symptom.

  ```py
  $ python -m pytest -vs -k test_ctrl_c
  =================================================== test session starts ====================================================
  platform linux -- Python 3.10.6, pytest-7.4.0, pluggy-1.2.0 -- YDBPython/.venv/bin/python
  cachedir: .pytest_cache
  rootdir: YDBPython
  plugins: repeat-0.9.1, order-1.1.0
  collected 552 items / 551 deselected / 1 selected

  tests/test_yottadb.py::test_ctrl_c Process Process-1:
  Traceback (most recent call last):
    File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
      self.run()
    File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
    File "YDBPython/tests/test_yottadb.py", line 1372, in infinite_set
      key.set("")
    File "YDBPython/yottadb/__init__.py", line 807, in set
      def set(self, value: AnyStr = "") -> None:
  KeyboardInterrupt
  FAILED

  ========================================================= FAILURES =========================================================
  _______________________________________________________ test_ctrl_c ________________________________________________________

  simple_data = None

      def test_ctrl_c(simple_data):
          def infinite_set():
              while True:
                  key = yottadb.Key("^x")
                  key.set("")

          process = multiprocessing.Process(target=infinite_set)

          process.start()
          time.sleep(0.5)
          psutil.Process(process.pid).send_signal(signal.SIGINT)
          process.join()

  >       assert process.exitcode == 254
  E       AssertionError: assert 1 == 254
  E        +  where 1 = <Process name='Process-1' pid=52662 parent=52655 stopped exitcode=1>.exitcode

  tests/test_yottadb.py:1381: AssertionError
  ================================================= short test summary info ==================================================
  FAILED tests/test_yottadb.py::test_ctrl_c - AssertionError: assert 1 == 254
  ============================================ 1 failed, 551 deselected in 0.69s =============================================
  ```

* Notice the `KeyboardInterrupt` message just before the `FAILED` line above. That indicates there was
  a Python exception (for keyboard interrupt). And is why the process terminated with an exit code of `1`.
  But the test expected the process to terminate with an exit code of `-2` (2 for SIGINT) which is equal to
  `256 - 2` i.e. `254`.

* It was puzzling why this happened only once in a while.

* The normal flow of events is that the YottaDB SIGINT signal handler will be in charge. When the test sends
  a SIGINT, the YottaDB signal handler notes down this occurrence for the process to terminate at a logical
  and safe point when we go out of the signal handler. As part of YottaDB/DB/YDB@ae2721d8, while inside the
  YottaDB signal handler, we also invoke any non-YottaDB signal handler if it is defined. In the case of
  Python, a handler is defined to handle Ctrl-C in case of a terminal and so that handler is invoked.
  I don't know for sure but suspect what that handler invocation does is note down in some Python-internal
  global variable that a SIGINT event occurred and immediately returned.

* Once we come out of the YottaDB SIGINT signal handler, the next YottaDB action would usually cause deferred
  signal handling to kick in and would result in the process terminating with an exit code of `-2`.

* But all this while Python is doing the same thing and waiting for some safe Python byte code to be reached
  at which point it will also do a check of any deferred signals.

* It is a race as to whether the Python check or YottaDB check for deferred signals happens first. It depends
  on where in the process execution the signal got actually delivered.

* If the Python check for deferred signals happens BEFORE the YottaDB check, then Python would invoke its
  Ctrl-C signal handler which would raise an exception and terminate the process with an exit code of `1`
  which is what causes the test failure once in a while.

Fix
---
* The fix is to enhance both the failing tests to have a `try` block to catch the `KeyboardInterrupt`
  exception and terminate the process with an exit code of `-2` in this case so it is in sync with the
  YottaDB exit code as well as passes the test in all runtime scenarios.